### ISSUE TITLE
final performance testing of vep (at merge)

### ISSUE THREAD

**Issue by averyniceday** [genome-nexus/genome-nexus-vep#2]
curl submission to the 350000 variant set previous used for testing ... into vep_wrapper image via api call.

**Comment by averyniceday** [comment]
Testing results bad input into VEP commandline tool:

**First Test (Bogus lines/string)**
- e.g BLHABA BAD STRING
- Result: Bad records skipped and excluded from the output file.

**Comment by mandawilson** [comment]
Deployed with kops, see [Testing VEP Wrapper in Kubernetes](https://docs.google.com/document/d/1-h9zRXl3yu-UpmL8Gb8ey4Lz51APeOF1HRlYu1byZms/edit?usp=sharing)

- [ ] Checkin this file on pipelines: /data/manda/knowledgesystems-k8s-deployment/genome-nexus/vep/gn_vep.yaml

**Comment by mandawilson** [comment]
RESULT: 28 minutes and 30 seconds.

vep@gn-vep-test-d45475d4c-wv5kv:~/src/ensembl-vep/input$ date; curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- 'http://localhost:8888/vep/human/region' < ~/src/ensembl-vep/input/impact.sorted.for_vep_350000_exact.txt > impact.sorted.for_vep_350000_exact.out1.json; date
Mon Mar  9 15:02:28 UTC 2020
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2018M    0 2009M  100 9163k  1203k   5487  0:28:30  0:28:29  0:00:01 5508k
Mon Mar  9 15:30:58 UTC 2020
